lighthouse can now be executed locally as well (#2)
* lighthouse can now be executed locally as well

* created the config file other than the yaml file

* height and width added to the img and number of runs increased to 4

* assertion removed and number of run decreased to 3

* cache npm packages during build

* upgrade actions/setup-node version

* increase number of runs to 4

* artifcats added to save the lighthouse result

* result store to heroku

* access the wizard build token as environment variable

* budget.json file added and storage target changed to public

* adding value for lighthouse assertion to be passed

Co-authored-by: Ang Sherpa <ang.sherpa@sinnerschrader.com>

diff --git a/.github/workflows/lighthouse-ci.yaml b/.github/workflows/lighthouse-ci.yaml
--- a/.github/workflows/lighthouse-ci.yaml
+++ b/.github/workflows/lighthouse-ci.yaml
@@ -1,20 +1,38 @@
 name: Build React project and run Lighthouse CI
-on: [push]
+on:
+  pull_request:
+    branches:
+      - master
 jobs:
   lhci:
     name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - name: Use Node.js 12.x
-        uses: actions/setup-node@v1
+      - uses: actions/checkout@v3
         with:
-          node-version: 12.x
-      - name: npm install, build
+          ref: ${{ github.event.pull_request.head.sha }}
+
+      - name: Use Node.js 14.x
+        uses: actions/setup-node@v3
+        with:
+          node-version: 14.x
+          cache: 'yarn'
+
+      - name: build and start the project
         run: |
-          npm install
-          npm run build
+          yarn install --immutable
+          yarn run build
+
       - name: run Lighthouse CI
         run: |
-          npm install -g @lhci/cli@0.8.x
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+          yarn global add @lhci/cli@0.8.x
+          lhci autorun || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+          LHCI_WIZARD_BUILD_TOKEN: ${{ secrets.LHCI_WIZARD_BUILD_TOKEN }}
+
+      - name: Save the result
+        uses: actions/upload-artifact@v1
+        with:
+          name: lighthouse-result
+          path: '.lighthouseci'
